spring:
  application:
    name: taskflow
  port:
    server: 8080
  datasource:
    url: jdbc:postgresql://localhost:5432/taskflow
    username: taskflow
    password: taskflow
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      connection-timeout: 2000